// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: my.proto

package my

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyClient is the client API for My service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type myClient struct {
	cc grpc.ClientConnInterface
}

func NewMyClient(cc grpc.ClientConnInterface) MyClient {
	return &myClient{cc}
}

func (c *myClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/my.My/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServer is the server API for My service.
// All implementations should embed UnimplementedMyServer
// for forward compatibility
type MyServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedMyServer should be embedded to have forward compatible implementations.
type UnimplementedMyServer struct {
}

func (UnimplementedMyServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafeMyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServer will
// result in compilation errors.
type UnsafeMyServer interface {
	mustEmbedUnimplementedMyServer()
}

func RegisterMyServer(s grpc.ServiceRegistrar, srv MyServer) {
	s.RegisterService(&My_ServiceDesc, srv)
}

func _My_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/my.My/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// My_ServiceDesc is the grpc.ServiceDesc for My service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var My_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "my.My",
	HandlerType: (*MyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _My_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my.proto",
}
